- rich-text-editor/ej2-javascript-rich-text-editor-toc.html
- rich-text-editor/ej2-typescript-rich-text-editor-toc.html
> documentation(EJ2-71942): issue resolved

- ej2-javascript/rich-text-editor/accessibility.md
- ej2-javascript/rich-text-editor/editor-modes.md
- ej2-javascript/rich-text-editor/ts/getting-started.md
> Documentation(833199): Fixed Broken link issue

- ej2-javascript/code-snippet/rich-text-editor/getting-started-cs12/index.js
- ej2-javascript/code-snippet/rich-text-editor/getting-started-cs12/index.ts
Keyboard Navigation Sample added the Format Painter Module and Item in the Toolbar
> bug(817060): UG documentation for format painter feature

- ej2-javascript/rich-text-editor/ej2-typescript-rich-text-editor-toc.html
- ej2-javascript/rich-text-editor/js/format-painter.md
- ej2-javascript/rich-text-editor/ts/format-painter.md
> documentation(835919): Fixed issues

- ej2-javascript/rich-text-editor/how-to/file-attachment.md
Bug(839505) : Resolved Publish error in Javascript
> Bug(839505) : Resolved Publish error in Javascript- development

- ej2-javascript/rich-text-editor/how-to/file-attachment.md
Bug(839505) : Resolved Publish error in Javascript
> Bug(839505) : Resolved Publish error in Javascript - HOTFIX

- ej2-javascript/rich-text-editor/editor-modes.md
- ej2-javascript/rich-text-editor/toolbar.md
- ej2-javascript/rich-text-editor/ts/getting-started.md
Resolved broken link issue for Rich Text editor component
> bug(839526): Resolved broken link issue for RichText editor component

- ej2-javascript/rich-text-editor/editor-modes.md
- ej2-javascript/rich-text-editor/toolbar.md
- ej2-javascript/rich-text-editor/ts/getting-started.md
Resolved broken link issue for Richtext editor component
> bug(839526): Resolved broken link issue for Rich text editor component

- ej2-javascript/code-snippet/rich-text-editor/how-to-check-file-size-cs1/index.js
- ej2-javascript/code-snippet/rich-text-editor/resizable-cs1/index.js
- ej2-javascript/code-snippet/rich-text-editor/toolbar-cs1/index.js
**Feature description**
The documentation preview sample is not working properly.
**Analysis / Design**
I have found that TS code is implemented in a JS file, so this preview sample is not working.
**Solution Description**
I have corrected the preview sample. TS code is implemented in a JS file, so this preview sample is not working.
**Areas affected and ensured**
This preview sample does not affect other cases and is guaranteed.
Did you included unit test cases.?
No
Is there any API name changes.?
No
/label ~bug
/assign [@ScrumMaster](https://github.com/ScrumMaster)
/cc [@ProductOwner](https://github.com/ProductOwner)
> Documentation(840572): The documentation preview sample is not working properly - Development

- ej2-javascript/code-snippet/rich-text-editor/how-to-check-file-size-cs1/index.js
- ej2-javascript/code-snippet/rich-text-editor/resizable-cs1/index.js
- ej2-javascript/code-snippet/rich-text-editor/toolbar-cs1/index.js
**Feature description**
The documentation preview sample is not working properly.
**Analysis / Design**
I have found that TS code is implemented in a JS file, so this preview sample is not working.
**Solution Description**
I have corrected the preview sample. TS code is implemented in a JS file, so this preview sample is not working.
**Areas affected and ensured**
This preview sample does not affect other cases and is guaranteed.
Did you included unit test cases.?
No
Is there any API name changes.?
No
/label ~bug
/assign [@ScrumMaster](https://github.com/ScrumMaster)
/cc [@ProductOwner](https://github.com/ProductOwner)
> Documentation(840572): The documentation preview sample is not working properly - Hotfix

- ej2-javascript/rich-text-editor/js/audio.md
- ej2-javascript/rich-text-editor/js/format-painter.md
- ej2-javascript/rich-text-editor/js/video.md
- ej2-javascript/rich-text-editor/ts/audio.md
- ej2-javascript/rich-text-editor/ts/getting-started.md
- ej2-javascript/rich-text-editor/ts/video.md
Need to resolve the Page With Redirect - EJ2 docs links for richtexteditor documentation
Resolved the Page With Redirect - EJ2 docs links for richtexteditor documentation by adding the correct links
NA
No area is affected due to this changes.
NA
NA
* Did you run the automation against your implementation? NA
* Is there any API name change? No
* Is there any existing behavior change of other features due to this code change? No
* Does your new code introduce new warnings or binding errors? No
* Does your code pass all FxCop and StyleCop rules? Yes
* Did you record this case in the unit test or UI test? NA
> documentation(839873): Add the correct path.

- ej2-javascript/rich-text-editor/toolbar.md
Prepare the text quick toolbar documentation for all platform
> feature(847256): Prepared the text quick toolbar documentation for all platform TS - Development

- ej2-javascript/rich-text-editor/keyboard-support.md
Need to update the Keyboard shortcuts in the Rich Text Editor Documentation after ensuring all the actions
I have ensured all the actions in the documentation and missing the audio and video shortcuts
This particular use case has not been tested previously.
No
No
I have updated the audio and video keyboard shortcuts in the Rich Text Editor component documentation.
Yes
No
No
No
 
/label ~bug
/assign @ScrumMaster
/cc @ProductOwner
> bug(860373): Need to update the Keyboard shortcuts in the Rich Text Editor Documentation after ensuring all the actions - Hotfix

- ej2-javascript/rich-text-editor/keyboard-support.md
Need to update the Keyboard shortcuts in the Rich Text Editor Documentation after ensuring all the actions
I have ensured all the actions in the documentation and missing the audio and video shortcuts
This particular use case has not been tested previously.
No
No
I have updated the audio and video keyboard shortcuts in the Rich Text Editor component documentation.
Yes
No
No
No
 
/label ~bug
/assign @ScrumMaster
/cc @ProductOwner
> bug(860373): Need to update the Keyboard shortcuts in the Rich Text Editor Documentation after ensuring all the actions - Development

- ej2-javascript/code-snippet/rich-text-editor/custom-tool-cs1/index.js
- ej2-javascript/code-snippet/rich-text-editor/custom-tool-cs1/index.ts
- ej2-javascript/rich-text-editor/toolbar.md
861631: Need to prepare documentation for custom toolbar root elementwith Css class.
> 861631: Need to prepare documentation for custom toolbar root elementwith Css class.

- ej2-javascript/rich-text-editor/js/getting-started.md
- ej2-javascript/rich-text-editor/ts/getting-started.md
Hello,
I have worked on links with redirects.
Regards,
Beryl.
> SEO-179239-Redirect-Links-TS

- ej2-javascript/rich-text-editor/accessibility.md
Need to modified the icons on accessibility document. The Icons are newly created for the compilance measuring.
[866555](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/866555)
NA
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Provide the details about the areas or combinations which have been tested against this code changes.
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX changes got approval if UI is …
> 866555: Need to modified the icons on accessibility document

- ej2-javascript/rich-text-editor/image.md
Hi @MallikaRK,
please review the changes made.
Thanks.
Regards,
Edith.
> SEO-178901-ej2-js-richtexteditor-redirect-links

- ej2-javascript/rich-text-editor/iframe.md
Hi @MallikaRK 
Worked on page with redirect for JS Rich Text.
Regards,
Sharly A>
> SEO-179237-JS-RichText-changes

- ej2-javascript/rich-text-editor/toolbar.md
Hi @MallikaRK
I have worked on links with redirects.
Regards,
Beryl.
> SEO-179239-Redirect-Links-TS2
